############# English navigation ##############

# main menu
[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Service"
url = "service/"
weight = 3

[[main]]
name = "Customers"
url = "project/"
weight = 4

[[main]]
name = "Team"
url = "team/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6

[[main]]
weight = 7
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Terms of Service"
  url = "terms/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Privacy Policy"
  url = "privacy-policy/"
  weight = 2

# footer menu
[[footer]]
name = "Terms of Service"
url = "terms/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2